### ISSUE TITLE
Segment thumbnails not showing

### ISSUE THREAD

**Issue by 202103817** [google-marketing-solutions/vigenair#25] opened 2024-10-11 11:16 UTC
<img width="172" alt="Screenshot 2024-10-11 121356" src="https://github.com/user-attachments/assets/3bb97dba-5044-41f3-ae24-c02ffa7ce4dd">

Hello, i was wondering why I can't seem to visualize the segement thumbnils in the ui. (see attached image)?

Thanks!

**Comment by mohabfekry** [comment] 2024-10-11 11:58
Hi! This is a duplicate of #23 which was fixed a couple of days ago. Please update your app (backend + frontend) to the latest version.

Thanks!

**Closed** 2024-10-11 11:58 UTC
